# rikipermana@live.com
name: Deploy api backend

on:
  push:
    branches: [ master ]

jobs:
  send-to-cmserver:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Send to CMSERVER
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: ./
        remote_path: ~/source/fast-api-test
        remote_host: ${{ secrets.HOST }}
        remote_port: 22
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.PRIVATE_KEY }}
        
  run-cmserver:
    runs-on: ubuntu-latest
    needs: [send-to-cmserver]
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Target Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: 22
        script: |
          cd ~/config-management-server
          ansible-playbook -i inventory playbooks/deploy/deploy-app-1.yml
